package com.iktpreobuka.projectfinal.entities;

public enum ESubjects {
	SERBIAN_LANGUAGE_AND_LITERATURE, MATHEMATICS, ENGLISH_LANGUAGE, FINE_ART, MUSIC,
	PHYSICAL_EDUCATION,HISTORY, BIOLOGY, GEOGRAPHY, PHYSICS, CHEMISTRY, INFORMATION_TECHNOLOGY
}
